name: Firebase Continuous Deployment
on: 
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v16
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - uses: jonahsnider/firebase-action@1.0.7
        env:
          PROJECT_ID: "google-cloud-or-firebase-project-id"
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        with:
          args: deploy
          
